### ISSUE TITLE
Ubuntu: Failed to configure repo 'postgresql-repo'

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/postgres-formula#161]
Deploy of postfix 9.6 on Ubuntu fails using upstream repo.

Replication
- Fresh vanilla installation of Ubuntu 16/17 & SALT 2017.17
- Pillars populated as per pillar.example but ...
https://github.com/saltstack-formulas/postgres-formula/blob/master/pillar.example
1. - Change version "9.3" to "9.6"
2. - Change "use_upstream_repo: True"

Output:
>
----------
          ID: postgresql-repo
    Function: pkgrepo.managed
      Result: False
     Comment: Failed to configure repo 'postgresql-repo': E: Malformed line 1 in source list /etc/apt/sources.list.d/pgdg.list (type)
              E: The list of sources could not be read.
     Started: 23:03:16.792033
    Duration: 2639.258 ms
     Changes:   
----------
>

**Comment by noelmcloughlin** [comment]
Need clarifying comment on pillar.example / README to help on-boarding experience.

Formula supports RedHat only, & Upstream supports Suse,Redhat, and Fedora only.

**Comment by ninapavlich** [comment]
Hi @noelmcloughlin have you found a good workaround or pillar configuration for Ubuntu + 9.6?

**Comment by noelmcloughlin** [comment]
Hi @ninapavlich, sorry I missed your question.  I'll have a look this week. Thx.

**Comment by noelmcloughlin** [comment]
Hey @ninapavlich, this formula would not work on vanilla Ubuntu 16.04, so this is workaround-

**Preparation:**

```
$ sudo rm -fr /var/lib/postgresql/
$ for p in $(dpkg-query --list | grep postgres | awk '{print $2}' ); do sudo apt-get -y --purge remove ${p}; done
$ sudo apt autoremove -y
$ for p in $(dpkg-query --list | grep postgres | awk '{print $2}' ); do sudo apt-get -y --purge remove $p; done
$ dpkg-query --list | grep postgres | awk '{print $2}'
```

highstate ...
```
base:
  '*':
    - postgres
    - postgres.python
```

pillar.example edits ...
```
postgres:
  use_upstream_repo: True
  version: '9.6'
  pkg: 'postgresql-9.6'
  pkg_client: 'postgresql-client-9.6'
  pkgs_extra:
  - postgresql-contrib-9.6
  - postgresql-plpython-9.6
  service: postgresql
 .... etc ....
```

**Result ...**

```
$ sudo salt-call state.highstate --local 

Succeeded: 19 (changed=12)
Failed:     0
Warnings:   1
-------------
Total states run:     19
Total run time:   80.198 s


$ dpkg-query --list | grep postgres | awk '{print $2}'
pgdg-keyring
postgresql-9.6
postgresql-client-9.6
postgresql-client-common
postgresql-common
postgresql-contrib-9.6
postgresql-plpython-9.6
```

Applying the states again throws a bug...

```
$ sudo salt-call state.highstate --local 
...
[ERROR   ] Command '['/usr/bin/psql', '--no-align', '--no-readline', '--no-psqlrc', '--no-password', '--dbname', 'postgres', '-c', 'CREATE TABLESPACE "my_space" OWNER "localUser" LOCATION \'/srv/my_tablespace\' ']' failed with return code: 1
[ERROR   ] stderr: ERROR:  directory "/srv/my_tablespace/PG_9.6_201608131" already in use as a tablespace
[ERROR   ] retcode: 1
[ERROR   ] Error connecting to Postgresql server
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/postgres_tablespace.py", line 121, in present
    if tblspaces[name]['Location'] != directory and not __opts__['test']:
KeyError: 'my_space'

Succeeded: 17 (changed=10)
Failed:     2
-------------
Total states run:     19
Total run time:   81.488 s
```

I think upstream packages are executing 'initdb' as part of postinstall because unless execution succeeds?

```
          ID: postgresql-cluster-prepared
    Function: cmd.run
        Name: pg_createcluster 9.6 main
      Result: True
     Comment: unless execution succeeded
     Started: 23:30:05.095115
    Duration: 96.124 ms
```

**Comment by noelmcloughlin** [comment]
will fix this in upcoming PRs.
