### ISSUE TITLE
postgres_tablespace.present noisy error

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/postgres-formula#186]
Formula could be improved to stop this noise.

```
[ERROR   ] Command '['/usr/bin/psql', '--no-align', '--no-readline', '--no-psqlrc', '--no-password', '--dbname', 'postgres', '-c', 'CREATE TABLESPACE "my_space" OWNER "localUser" LOCATION \'/srv/my_tablespace\' ']' failed with return code: 1
[ERROR   ] stderr: ERROR:  directory "/srv/my_tablespace/PG_9.5_201510051" already in use as a tablespace
[ERROR   ] retcode: 1
[ERROR   ] Error connecting to Postgresql server
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1851, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/states/postgres_tablespace.py", line 121, in present
    if tblspaces[name]['Location'] != directory and not __opts__['test']:
KeyError: 'my_space'

          ID: postgres_tablespace-my_space
    Function: postgres_tablespace.present
        Name: my_space
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/postgres_tablespace.py", line 121, in present
                  if tblspaces[name]['Location'] != directory and not __opts__['test']:
              KeyError: 'my_space'
     Started: 00:39:53.970815
    Duration: 1149.198 ms
     Changes:
```

**Comment by noelmcloughlin** [comment]
Always happens on Centos

**Comment by noelmcloughlin** [comment]
Happens on Fedora 27 too.  Never happens on ubuntu.

**Comment by noelmcloughlin** [comment]
The `0700` permissions on {{ tablespace }} must be the problem.
```
[ERROR   ] Command '['/usr/bin/psql', '--no-align', '--no-readline', '--no-psqlrc', '--no-password', '--dbname', 'postgres', '-c', 'CREATE TABLESPACE "my_space" OWNER "localUser" LOCATION \'/srv/my_tablespace\' ']' failed with return code: 1
[ERROR   ] stderr: ERROR:  could not set permissions on directory "/srv/my_tablespace": Permission denied
[ERROR   ] retcode: 1
[ERROR   ] Error connecting to Postgresql server
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1851, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/postgres_tablespace.py", line 121, in present
    if tblspaces[name]['Location'] != directory and not __opts__['test']:
KeyError: 'my_space'
```
Actual permissions:
```
$ ls -l /srv/ | grep table
drwx------. 2 postgres postgres 4096 Mar 21 17:06 my_tablespace
```

**Comment by noelmcloughlin** [comment]
Will try adding `postgres.selinux.enabled: False` state before CREATE TABLESPACE

**Comment by noelmcloughlin** [comment]
**Further issue to be fixed in this formula-** 

cut+paste from https://github.com/saltstack/salt/pull/50045

> Looking at the original issue from the postgres-formula repo, I think these changes doesn't not resolve the issue at all. The state will try to create the same tablespace on each state run and we're going simply to mask that.
> The "KeyError" exception looks deceptive, because it hides the original problem. That needs to be fixed though.
